apiVersion: v1
kind: Service
metadata:
  name: url-monitor-service
  labels:
    app: url-monitor
spec:
  type: NodePort
  selector:
    app: url-monitor
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080  # Access on host:30080
    protocol: TCP
    name: http